### ISSUE TITLE
CRAN check fails

### ISSUE THREAD

**Issue by tscheypidi** [pik-piam/citation#11]
Hi @wleoncio,

I got a mail from CRAN:

> Dear maintainer,
>
>Please see the problems shown on
[<https://cran.r-project.org/web/checks/check_results_citation.html>](https://cran.r-project.org/web/checks/check_results_citation.html).
>
> Apparently your package fails its checks in a strict Latin-1* locale,
> e.g. under Linux using LANG=en_US.iso88591 (see the debian-clang
> results).
>
> Please correct before 2022-08-30 to safely retain your package on CRAN.
>
> Best,
> -k

I did a quick check and could reproduce the error message via `rhub::check(platform="debian-clang-devel")`, but I have no idea why the check is failing. Could you have a look at it? Perhaps it is related to the `cat` call at https://github.com/pik-piam/citation/blob/master/R/r2cff.R#L51 ?

**Comment by wleoncio** [comment]
Sure thing, I'm on it! :)
