### ISSUE TITLE
Any planned CRAN updates?

### ISSUE THREAD

**Issue by wleoncio** [pik-piam/citation#9]
Hey guys,

I was wondering if there are any plans to release citation 0.6.1 on CRAN. I'm planning on promoting it to my work mates during an event this spring, and it would be nice to just have them conveniently install the latest version from CRAN other than GitHub.

Here's to a great 2022! 🥂

**Comment by tscheypidi** [comment]
Hej Waldir, 

I can make another submission to CRAN. Is the current version the one you would like to see on CRAN or should I wait for another PR. From our side there are currently no updates in the making.

**Comment by wleoncio** [comment]
Thanks Jan, that's great to hear! No upcoming changes on my side either, the most important features for me are in (bidirectional conversion from R to CFF). As far as future contributions to this package go, I can foresee some patches to bugs we find while using the software as well as some more test units (I might be going through a bit of a codecov-obsession phase).

**Comment by tscheypidi** [comment]
The package is now on its way to CRAN and should be available soon
